system Weather/Rain
{
    fast_forward                                1 1
    category                                    Nature
    technique 
    {
        visual_particle_quota                   5000
        material                                PU/Weather/Rain
        default_particle_width                  0.24
        default_particle_height                 12
        renderer                                Billboard
        {
            billboard_type                      oriented_self
            billboard_origin                    top_center
        }
        emitter                                 Box 
        {
            emission_rate                       500
            angle                               1
            time_to_live                        2
            velocity                            75
            position                            0 48 0
            direction                           0.2 -1 0
            box_width                           1024
            box_height                          16
            box_depth                           1024
        }
        // this observer is manipulated in code
        // and will delete the particle
        observer                                OnPosition 
        {
            position_y                          less_than 0.0
        }
    }
}
