@ECHO OFF

SET CONVERTER="../OgreTools/OgreXMLConverter.exe"
SET MODELPATH=../../Resources/models/%1%/
SET FILENAME=%1%.mesh
SET FULLPATH=%MODELPATH%%FILENAME%
SET COMMAND=%CONVERTER% %FULLPATH%

%COMMAND%
