#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18033
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Meridian59.Android.ChatClient.Resource", IsApplication=true)]

namespace Meridian59.Android.ChatClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001c
			public const int btnLogin = 2131034140;
			
			// aapt resource value: 0x7f050013
			public const int btnRest = 2131034131;
			
			// aapt resource value: 0x7f050023
			public const int btnSelect = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int cbSelect = 2131034146;
			
			// aapt resource value: 0x7f050000
			public const int charSelectItem = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int listChat = 2131034113;
			
			// aapt resource value: 0x7f050024
			public const int listPlayers = 2131034148;
			
			// aapt resource value: 0x7f05001e
			public const int menu_chat = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int menu_disconnect = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int menu_info = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int menu_send = 2131034143;
			
			// aapt resource value: 0x7f050021
			public const int menu_wholist = 2131034145;
			
			// aapt resource value: 0x7f050003
			public const int tableLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int tableRow1 = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int tableRow2 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int tableRow3 = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int tableRow4 = 2131034128;
			
			// aapt resource value: 0x7f050004
			public const int tableRow5 = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int textItem = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int textView10 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int textView11 = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int textView12 = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int textView18 = 2131034129;
			
			// aapt resource value: 0x7f050005
			public const int textView21 = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int textView5 = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int textView6 = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int textView7 = 2131034136;
			
			// aapt resource value: 0x7f05000c
			public const int txtHP = 2131034124;
			
			// aapt resource value: 0x7f050019
			public const int txtHost = 2131034137;
			
			// aapt resource value: 0x7f050006
			public const int txtLatency = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int txtMP = 2131034127;
			
			// aapt resource value: 0x7f050017
			public const int txtPassword = 2131034135;
			
			// aapt resource value: 0x7f05001b
			public const int txtPort = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int txtPortDesc = 2131034138;
			
			// aapt resource value: 0x7f050009
			public const int txtRoom = 2131034121;
			
			// aapt resource value: 0x7f050015
			public const int txtUsername = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int txtVigor = 2131034130;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CharSelectItemView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Chat = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChatItemView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Info = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SelectAvatar = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WhoList = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
